export enum ActionTypes {
  GET_ALL_PUBLICATIONS = "GET_ALL_PUBLICATIONS",
  GET_ALL_PUBLICATIONS_LOADING = "GET_ALL_PUBLICATIONS_LOADING",
  GET_ALL_PUBLICATIONS_ERROR = "GET_ALL_PUBLICATIONS_ERROR",
}
